name = "mercedes-benz-links"
main = ".open-next/worker.js"
compatibility_date = "2026-05-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_APP_URL = "https://mercedes-benz-links.workers.dev"
ALLOWED_ORIGINS = "https://mercedes-benz-links.workers.dev"
